version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - checkout
      - run:
          command: |
            git submodule sync
            git submodule update --init
            hugo --minify
            mkdir -p ~/tmp/public
            cp -r ~/hugo/public/ ~/tmp/public
            git checkout master
            rm -r ~/hugo/*
            cp ~/tmp/public/ ~/hugo/
            git config --global user.name ${GITHUB_USER_NAME}
            git config --global user.email ${GITHUB_USER_MAIL}
            git add -A
            git commit -m "push by circle ci"
            git push origin master
