version: 2
docker:
  - image: cibuilds/hugo:latest
working_directory: ~/hugo

jobs:
  checkout_code:
    steps:
      - run:
          command: |
            chmod -R 777 ~/hugo
      - checkout
      - save_cache:
          key: hugo-cache-{{ epoch }}
          paths:
            - ~/hugo

  build:
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
          command: |
            git submodule sync
            git submodule update --init
            hugo --minify
            mkdir -p ~/public
            chmod -R 777 ~/public
            cp -r ~/hugo/public ~/public
      - save_cache:
          key: hugo-cache-public-{{ epoch }}
          paths:
            - ~/public

  deploy:
    machine:
      enabled: true
    steps:
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            git config --global user.name ${GITHUB_USER_NAME}
            git config --global user.email ${GITHUB_USER_MAIL}
            git checkout master
            git rm -r *
            cp ~/public/ .
            git add -A
            git commit -m "push by circle ci"
            git push origin master

workflows:
  version: 2
  build_and_deploy:
    filters:
      branches:
        only: write
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - build
