version: 2

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    steps:
      - restore_cache:
          key: hugo-cache
      - run:
          command: |
            git submodule sync
            git submodule update --init
            hugo --minify
            mkdir -p ~/public
            chmod -R 777 ~/public
            cp -r ~/hugo/public ~/public
      - save_cache:
          key: hugo-cache-public-{{ epoch }}
          paths:
            - ~/public

  deploy:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    machine:
      enabled: true
    steps:
      - restore_cache:
          key: hugo-cache-public
      - run:
          command: |
            git config --global user.name ${GITHUB_USER_NAME}
            git config --global user.email ${GITHUB_USER_MAIL}
            git checkout master
            git rm -r *
            cp ~/public/ .
            git add -A
            git commit -m "push by circle ci"
            git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - deploy:
          filters:
            branches:
              only: write
          requires:
            - build
